### ISSUE TITLE
Update for use with Cypress 3.0

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress-example-docker-circle#10]
- cache `~/.npm` and `~/.cache`
- don't cache node_modules

**Comment by AlbertBrand** [comment]
Also multi reporter setup needs a change, as the test suites are now run separately and would overwrite the previous report otherwise:
```
{
  "reporterEnabled": "spec, mocha-junit-reporter",
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "multiple-results/results.[hash].xml"
  }
}
```
